# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fcc8041ed803b369f01c709d5ae5bd7094490c285b60dbf0548b76d298a92018d7a0d53edb5172ae99a83cd87032466434db08c43d7dd0268177e04065666ba

test:
  secret_key_base: 0b879c062f1b1d25cd963c8bf60a0127d5edf45472132f43b40791a50272e61558c1c00709cff97c965b902fa6d4f6a2dc5f547e695ab27f7b4c1dc241a80146

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
